# SPDX-FileCopyrightText: 2024-2025 Pagefault Games
#
# SPDX-License-Identifier: CC-BY-NC-SA-4.0
version: "2"
run:
  timeout: 10m
severity:
  default: error
  rules:
    - linters:
        - unused
      severity: info
